# Dockerfile for Firedrake with a full set of capabilities installed.

FROM firedrakeproject/firedrake:latest

# install fixed branch of firedrake-ts
ARG BRANCH="2026.4-fixes"

RUN git clone --branch ${BRANCH} https://github.com/mspieg/firedrake-ts.git /opt/firedrake-ts \
    &&  pip install --verbose /opt/firedrake-ts

     
     

